# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./

    - name: Test
      run: go test -v ./...
    - name: mkwebsitedir
      run: mkdir website
    - uses: actions/checkout@v3
      with:
        repository: 'webra2/webra2'
        path: website
        token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: download-cd
      run: ./go-download-web
    - name: push
      run: |
        cd website
        ls -R -l
        git config --local user.email "webra2@webra2.com"
        git config --local user.name "webra2"
        bash ../deploy.sh

    
